function df_depth_1_dT = df_depth_1_dt(in1)
%DF_DEPTH_1_DT
%    DF_DEPTH_1_DT = DF_DEPTH_1_DT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    26-Dec-2016 14:33:13

x_2_norm = in1(7,:);
df_depth_1_dT = [1.0,0.0,-x_2_norm];
