function df_depth_2_dT = df_depth_2_dt(in1)
%DF_DEPTH_2_DT
%    DF_DEPTH_2_DT = DF_DEPTH_2_DT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    26-Dec-2016 14:33:13

y_2_norm = in1(8,:);
df_depth_2_dT = [0.0,1.0,-y_2_norm];
